var app = angular.module('myApp.projects', ['ui.router', 'bootstrapLightbox']);

app.controller('ProjectsCtrl', function ($scope, Lightbox) {
  $scope.allProjects = [
    {name:'Vynle Wrap', image:'vynleWrap/main.jpg', link:'vynleWrap'},
    {name:'Midi Controller', image:'midiController/18.jpg', link:'midiController'},
    {name:'Web Class Final Project', image:'webFinal/main.jpg', link:'webFinal'},
    {name:'Bathroom Remodel', image:'bathroom/29.jpg', link:'bathroom'},
    {name:'Orion Mobile App', image:'orionApp/orionApp.jpg', link:'bathroom'}
  ];

  $scope.midiController = [
    {
      'url':'public/images/midiController/0.jpg',
      'thumbUrl':'0.jpg.small'
    },
    {
      'url':'public/images/midiController/10.jpg',
      'thumbUrl':'10.jpg.small'
    },
    {
      'url':'public/images/midiController/11.jpg',
      'thumbUrl':'11.jpg.small'
    },
    {
      'url':'public/images/midiController/12.jpg',
      'thumbUrl':'12.jpg.small'
    },
    {
      'url':'public/images/midiController/13.jpg',
      'thumbUrl':'13.jpg.small'
    },
    {
      'url':'public/images/midiController/14.jpg',
      'thumbUrl':'14.jpg.small'
    },
    {
      'url':'public/images/midiController/15.jpg',
      'thumbUrl':'15.jpg.small'
    },
    {
      'url':'public/images/midiController/16.jpg',
      'thumbUrl':'16.jpg.small'
    },
    {
      'url':'public/images/midiController/17.jpg',
      'thumbUrl':'17.jpg.small'
    },
    {
      'url':'public/images/midiController/18.jpg',
      'thumbUrl':'18.jpg.small'
    },
    {
      'url':'public/images/midiController/19.jpg',
      'thumbUrl':'19.jpg.small'
    },
    {
      'url':'public/images/midiController/1.jpg',
      'thumbUrl':'1.jpg.small'
    },
    {
      'url':'public/images/midiController/20.jpg',
      'thumbUrl':'20.jpg.small'
    },
    {
      'url':'public/images/midiController/21.jpg',
      'thumbUrl':'21.jpg.small'
    },
    {
      'url':'public/images/midiController/2.jpg',
      'thumbUrl':'2.jpg.small'
    },
    {
      'url':'public/images/midiController/3.jpg',
      'thumbUrl':'3.jpg.small'
    },
    {
      'url':'public/images/midiController/4.jpg',
      'thumbUrl':'4.jpg.small'
    },
    {
      'url':'public/images/midiController/5.jpg',
      'thumbUrl':'5.jpg.small'
    },
    {
      'url':'public/images/midiController/6.jpg',
      'thumbUrl':'6.jpg.small'
    },
    {
      'url':'public/images/midiController/7.jpg',
      'thumbUrl':'7.jpg.small'
    },
    {
      'url':'public/images/midiController/8.jpg',
      'thumbUrl':'8.jpg.small'
    },
    {
      'url':'public/images/midiController/9.jpg',
      'thumbUrl':'9.jpg.small'
    }  
  ]

  $scope.bathroom = [
    {
      'url':'public/images/bathroom/10.jpg',
      'thumbUrl':'10.jpg.small'
    },
    {
      'url':'public/images/bathroom/11.jpg',
      'thumbUrl':'11.jpg.small'
    },
    {
      'url':'public/images/bathroom/12.jpg',
      'thumbUrl':'12.jpg.small'
    },
    {
      'url':'public/images/bathroom/13.jpg',
      'thumbUrl':'13.jpg.small'
    },
    {
      'url':'public/images/bathroom/14.jpg',
      'thumbUrl':'14.jpg.small'
    },
    {
      'url':'public/images/bathroom/15.jpg',
      'thumbUrl':'15.jpg.small'
    },
    {
      'url':'public/images/bathroom/16.jpg',
      'thumbUrl':'16.jpg.small'
    },
    {
      'url':'public/images/bathroom/17.jpg',
      'thumbUrl':'17.jpg.small'
    },
    {
      'url':'public/images/bathroom/18.jpg',
      'thumbUrl':'18.jpg.small'
    },
    {
      'url':'public/images/bathroom/19.jpg',
      'thumbUrl':'19.jpg.small'
    },
    {
      'url':'public/images/bathroom/1.jpg',
      'thumbUrl':'1.jpg.small'
    },
    {
      'url':'public/images/bathroom/20.jpg',
      'thumbUrl':'20.jpg.small'
    },
    {
      'url':'public/images/bathroom/21.jpg',
      'thumbUrl':'21.jpg.small'
    },
    {
      'url':'public/images/bathroom/22.jpg',
      'thumbUrl':'22.jpg.small'
    },
    {
      'url':'public/images/bathroom/23.jpg',
      'thumbUrl':'23.jpg.small'
    },
    {
      'url':'public/images/bathroom/24.jpg',
      'thumbUrl':'24.jpg.small'
    },
    {
      'url':'public/images/bathroom/25.jpg',
      'thumbUrl':'25.jpg.small'
    },
    {
      'url':'public/images/bathroom/26.jpg',
      'thumbUrl':'26.jpg.small'
    },
    {
      'url':'public/images/bathroom/27.jpg',
      'thumbUrl':'27.jpg.small'
    },
    {
      'url':'public/images/bathroom/28.jpg',
      'thumbUrl':'28.jpg.small'
    },
    {
      'url':'public/images/bathroom/29.jpg',
      'thumbUrl':'29.jpg.small'
    },
    {
      'url':'public/images/bathroom/2.jpg',
      'thumbUrl':'2.jpg.small'
    },
    {
      'url':'public/images/bathroom/30.jpg',
      'thumbUrl':'30.jpg.small'
    },
    {
      'url':'public/images/bathroom/31.jpg',
      'thumbUrl':'31.jpg.small'
    },
    {
      'url':'public/images/bathroom/32.jpg',
      'thumbUrl':'32.jpg.small'
    },
    {
      'url':'public/images/bathroom/3.jpg',
      'thumbUrl':'3.jpg.small'
    },
    {
      'url':'public/images/bathroom/4.jpg',
      'thumbUrl':'4.jpg.small'
    },
    {
      'url':'public/images/bathroom/5.jpg',
      'thumbUrl':'5.jpg.small'
    },
    {
      'url':'public/images/bathroom/6.jpg',
      'thumbUrl':'6.jpg.small'
    },
    {
      'url':'public/images/bathroom/7.jpg',
      'thumbUrl':'7.jpg.small'
    },
    {
      'url':'public/images/bathroom/8.jpg',
      'thumbUrl':'8.jpg.small'
    },
    {
      'url':'public/images/bathroom/9.jpg',
      'thumbUrl':'9.jpg.small'
    }
  ];
  $scope.midiControllerModal = function (index) {
    Lightbox.openModal($scope.midiController, index);
  };
  $scope.bathroomModal = function (index) {
    Lightbox.openModal($scope.bathroom, index);
  };
    
});
